name: InfuseQuest

version: 1.0

main: com.infusequest.InfuseQuest

api-version: '1.21'


depend:

  - Infuse


commands:

  quests:

    description: Open daily quests


  infusepower:

    description: Open power upgrade menu


  iq:

    description: Admin commands


  powers:

    description: Open Infuse Power Menu


permissions:


  infusequest.admin:

    default: op


softdepend:
  - InfuseSMP


commands:
  infusedebug:
    description: Debug Infuse API